// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Plan is exactly what pressing the button will do. Shown first, always.
 */
export interface Plan {
    "id": string;
    "kind": string;
    "command"?: string;
    "path"?: string;
    "diff"?: string;
    "note"?: string;
    "error"?: string;
}

/**
 * Result is what happened, including the part we could not do.
 */
export interface Result {
    "ok": boolean;
    "output"?: string;
    "verified": boolean;
    "backup"?: string;
    "error"?: string;

    /**
     * * The same command, for a person who would rather run it themselves.
     */
    "command"?: string;

    /**
     * * Which config file was written, when one was.
     */
    "path"?: string;
}

/**
 * Status is what the settings window shows before anything is pressed.
 */
export interface Status {
    "id": string;
    "label": string;
    "kind": string;
    "installed": boolean;
    "connected": boolean;

    /**
     * *
     * 	 * Nobody has asked this one yet whether the board is in its configuration.
     * 	 *
     * 	 * Only a CLI client can be in this state, and only because asking means
     * 	 * running it: `claude mcp list` costs four seconds on a plain machine, all of
     * 	 * it node starting up. "Installed?" is a stat call; "connected?" is a
     * 	 * subprocess. Reporting Connected: false before asking would be a lie with a
     * 	 * button attached to it, so the two answers travel separately.
     */
    "asking": boolean;

    /**
     * * Where we looked: the binary we found, or the config file we read.
     */
    "detail": string;
    "path"?: string;
    "note"?: string;
    "docs"?: string;
}
