// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as app$0 from "../../../../FMakareev/muster-backlog/internal/app/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "muster:bulk:progress": app$0.BulkProgress;
            "muster:project:changed": app$0.ProjectChanged;
            "muster:registry:changed": {};
        }
    }
}
