// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the whole of Muster's own preferences.
 */
export interface Settings {
    /**
     * OnWindowClose is quit or tray. Neither is right for everyone, so this is
     * a preference rather than a decision.
     */
    "onWindowClose": WindowBehaviour;

    /**
     * TaskView is how an opened task is shown.
     */
    "taskView": TaskView;

    /**
     * GroupBy is what the board groups cards by: empty, project or milestone.
     */
    "groupBy": string;

    /**
     * WIPLimits are advisory ceilings on how many tasks a project may have in
     * a status, keyed by status name. They are counted from native data and
     * never enforced - a limit that blocks a drag is a limit people work
     * around rather than a signal they act on.
     */
    "wipLimits": { [_ in string]?: number } | null;

    /**
     * StaleAfterDays is when an untouched open task is called stale.
     */
    "staleAfterDays": number;

    /**
     * ScalePercent scales the whole interface. The default density suits a
     * board over nine projects and suits nobody who needs larger type, so it
     * is a choice rather than a constraint.
     */
    "scalePercent": number;
}

/**
 * TaskView is where a task is shown when it is opened.
 */
export enum TaskView {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ViewPanel is the column against the edge of the window.
     */
    ViewPanel = "panel",

    /**
     * ViewCentred is a reading view over the middle of the board, which is
     * easier on a wide screen where the edge is a long way from the eye.
     */
    ViewCentred = "centred",
};

/**
 * WindowBehaviour is what happens when the window is closed.
 */
export enum WindowBehaviour {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * BehaviourQuit closes the application, like an ordinary window.
     */
    BehaviourQuit = "quit",

    /**
     * BehaviourTray leaves it resident in the system tray.
     */
    BehaviourTray = "tray",
};
