// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the whole of Muster's own preferences.
 */
export interface Settings {
    /**
     * OnWindowClose is quit or tray. Neither is right for everyone, so this is
     * a preference rather than a decision.
     */
    "onWindowClose": WindowBehaviour;

    /**
     * TaskView is how an opened task is shown.
     */
    "taskView": TaskView;

    /**
     * GroupBy is what the board groups cards by: empty, project or milestone.
     */
    "groupBy": string;
}

/**
 * TaskView is where a task is shown when it is opened.
 */
export enum TaskView {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ViewPanel is the column against the edge of the window.
     */
    ViewPanel = "panel",

    /**
     * ViewCentred is a reading view over the middle of the board, which is
     * easier on a wide screen where the edge is a long way from the eye.
     */
    ViewCentred = "centred",
};

/**
 * WindowBehaviour is what happens when the window is closed.
 */
export enum WindowBehaviour {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * BehaviourQuit closes the application, like an ordinary window.
     */
    BehaviourQuit = "quit",

    /**
     * BehaviourTray leaves it resident in the system tray.
     */
    BehaviourTray = "tray",
};
