// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Class is the directory an entity was found in.
 * 
 * It is part of an entity's identity, not decoration: ids are unique only
 * within one directory of one project. Archiving is a soft delete and the CLI
 * reuses archived ids, so the same id can name two different tasks in tasks/
 * and archive/tasks/ at once. That happens in the author's own projects today.
 */
export enum Class {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The directory classes an entity can be found in.
     */
    ClassActive = "active",
    ClassCompleted = "completed",
    ClassArchived = "archived",
};

/**
 * Comment is one entry from a task's comment envelope.
 */
export interface Comment {
    "Author": string;

    /**
     * Created is the raw timestamp. Unlike every frontmatter date it is not
     * quoted in the file, and it is kept as written rather than parsed, since
     * nothing depends on its type.
     */
    "Created": string;
    "Body": string;
}

/**
 * Criterion is one acceptance-criteria or definition-of-done item.
 */
export interface Criterion {
    /**
     * Index is the 1-based handle the CLI uses for --check-ac. It is
     * renumbered on insertion and deletion, so it identifies an item only
     * within one revision of one file and must never be persisted as identity.
     */
    "Index": number;

    /**
     * Checked is the [x] state.
     */
    "Checked": boolean;

    /**
     * Text is everything after the marker, verbatim.
     */
    "Text": string;
}

/**
 * Entity is any Backlog.md file: a task, draft, milestone, document or decision.
 */
export interface Entity {
    "Kind": Kind;
    "Class": Class;
    "ID": string;

    /**
     * Path is the file this was read from.
     */
    "Path": string;

    /**
     * Title always comes from frontmatter. Filenames are a lossy, one-way
     * derivation - only a fifth of them survive the round trip, and five in the
     * author's projects carry no title information at all.
     */
    "Title": string;
    "Status": string;
    "Priority": string;
    "Type": string;
    "Assignee": string[] | null;
    "Labels": string[] | null;

    /**
     * Milestone is an id or a title, depending on how it was written.
     */
    "Milestone": string;

    /**
     * Dependencies, ParentTaskID and Subtasks reference other entities. Every
     * such reference resolves inside its own project only: ids collide across
     * projects freely.
     */
    "Dependencies": string[] | null;
    "ParentTaskID": string;
    "Subtasks": string[] | null;

    /**
     * Ordinal holds manual ordering. It is optional and not unique.
     */
    "Ordinal": number | null;
    "HasOrdinal": boolean;
    "Created": string;
    "Updated": string;

    /**
     * Date is a decision's own date field.
     */
    "Date": string;
    "References": string[] | null;
    "Documentation": string[] | null;
    "ModifiedFiles": string[] | null;
    "Tags": string[] | null;

    /**
     * Reporter and OnStatusChange are in the 1.48.0 serialiser but appear in no
     * file the corpus contains. Read, never required.
     */
    "Reporter": string;
    "OnStatusChange": string;

    /**
     * Sections holds the delimited regions of a task body. Absent sections are
     * absent from the map; a present but empty section maps to "".
     */
    "Sections": { [_ in Section]?: string } | null;

    /**
     * AcceptanceCriteria and DefinitionOfDone are parsed items. An empty,
     * present section yields a non-nil empty slice, because "no criteria" and
     * "no section" are different states.
     */
    "AcceptanceCriteria": Criterion[] | null;
    "DefinitionOfDone": Criterion[] | null;
    "Comments": Comment[] | null;

    /**
     * Body is everything after the frontmatter, verbatim and CRLF-normalised.
     * Non-task entities have no marker grammar at all, so for them this is the
     * whole of their content.
     */
    "Body": string;
}

/**
 * Kind is the sort of entity a file holds.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The entity kinds Backlog.md defines.
     */
    KindTask = "task",
    KindDraft = "draft",
    KindMilestone = "milestone",
    KindDocument = "document",
    KindDecision = "decision",
};

/**
 * Section is one delimited region of a task body.
 */
export enum Section {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The delimited regions a task body can carry.
     */
    SectionDescription = "description",
    SectionPlan = "plan",
    SectionNotes = "notes",
    SectionFinalSummary = "final_summary",
};
