// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoardService is the frontend's only entry point to the backend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddLabel adds a label to a task without touching the others.
 */
export function AddLabel(projectPath: string, taskID: string, label: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(3047498661, projectPath, taskID, label);
}

/**
 * AddProject registers an existing folder.
 * 
 * The folder must already hold a Backlog.md project: registering a folder that
 * does not is how a board fills with entries that explain themselves as broken.
 * Initialising is a separate, deliberate act.
 */
export function AddProject(path: string, edit: $models.ProjectEdit): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2556526182, path, edit);
}

/**
 * Analytics returns the cross-project overview.
 */
export function Analytics(): $CancellablePromise<$models.AnalyticsView[] | null> {
    return $Call.ByID(940557558);
}

/**
 * CLIVersion reports the CLI version in use, empty when there is none.
 */
export function CLIVersion(): $CancellablePromise<string> {
    return $Call.ByID(3640242740);
}

/**
 * CanChooseFolder reports whether the interface should offer a browse button.
 * 
 * Asked rather than assumed: the same frontend runs in the server build, which
 * has no dialogs at all, and a button that can only fail is worse than no
 * button.
 */
export function CanChooseFolder(): $CancellablePromise<boolean> {
    return $Call.ByID(2421757485);
}

/**
 * CanMove reports whether a task in a project may take a status.
 * 
 * A task can only ever hold a status its own project declares; anything else
 * would be a value the Backlog.md CLI itself rejects.
 */
export function CanMove(projectPath: string, status: string): $CancellablePromise<boolean> {
    return $Call.ByID(3472873825, projectPath, status);
}

/**
 * CaptureDraft writes text into a project's drafts.
 */
export function CaptureDraft(projectPath: string, title: string, description: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(4046319439, projectPath, title, description);
}

/**
 * CheckCriterion ticks or unticks an acceptance criterion by its 1-based index.
 */
export function CheckCriterion(projectPath: string, taskID: string, index: number, checked: boolean): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2097427485, projectPath, taskID, index, checked);
}

/**
 * ChooseFolder opens the desktop's own directory chooser.
 * 
 * Returns the folder, or "" when the person cancelled - which is not an error
 * and must not be reported as one. Where there is no dialog at all, the
 * interface has already hidden the button; this still answers "" rather than
 * failing, so a stale window cannot produce a broken state.
 */
export function ChooseFolder(): $CancellablePromise<string> {
    return $Call.ByID(3013292659);
}

/**
 * CreateTask writes a new task into a project.
 */
export function CreateTask(input: $models.NewTaskInput): $CancellablePromise<$models.CreateResult> {
    return $Call.ByID(2184482871, input);
}

/**
 * DiscardDraft archives a draft.
 * 
 * Archiving rather than deleting: Backlog.md has no delete, and a note
 * captured in a hurry is exactly the kind of thing someone wants back.
 */
export function DiscardDraft(projectPath: string, draftID: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2408719147, projectPath, draftID);
}

/**
 * Drafts returns every waiting draft, oldest first.
 * 
 * Oldest first because that is the order an inbox has to be emptied in: the
 * note that has been ignored longest is the one that most needs a decision.
 * Archived drafts are not here - discarding one is how it leaves.
 */
export function Drafts(): $CancellablePromise<$models.DraftView[] | null> {
    return $Call.ByID(859692890);
}

/**
 * Entities returns every document, decision, draft or milestone across every
 * project, so the viewer can list them without asking for tasks it will drop.
 */
export function Entities(kind: string): $CancellablePromise<$models.TaskView[] | null> {
    return $Call.ByID(1843672625, kind);
}

/**
 * FilterValues returns the distinct values of one field across every project,
 * for building filter menus.
 */
export function FilterValues(field: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3592693646, field);
}

/**
 * InitProject initialises a folder as a Backlog.md project and registers it.
 * 
 * The two halves are one action deliberately: a folder initialised and then
 * not registered is work the person would have to repeat, and the CLI has
 * already written to the folder by then.
 */
export function InitProject(form: $models.InitFolder): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2783514793, form);
}

/**
 * InspectFolder reports what a folder is, before anything is written to it.
 */
export function InspectFolder(path: string): $CancellablePromise<$models.FolderView> {
    return $Call.ByID(638733642, path);
}

/**
 * Layout returns the unified board columns.
 * 
 * Statuses are per-project configuration and projects do not agree, so the
 * columns are the union of every declared list. Muster never edits another
 * project's config to make its own view simpler.
 */
export function Layout(): $CancellablePromise<$models.BoardLayout> {
    return $Call.ByID(1111036648);
}

/**
 * Milestones returns every milestone across every project, in registry order.
 * 
 * A card carries its milestone as a bare id, which reads exactly like a task
 * id and says nothing. This is what lets the interface show the title instead.
 */
export function Milestones(): $CancellablePromise<$models.MilestoneView[] | null> {
    return $Call.ByID(4122282057);
}

/**
 * MoveProject puts a project at a position in the registry, which is the order
 * it appears in everywhere.
 */
export function MoveProject(path: string, to: number): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(1970489624, path, to);
}

/**
 * Problems returns everything currently wrong.
 * 
 * Standing conditions come first: a missing CLI matters more than a stray file
 * in a task directory, and it is the one a person has to act on.
 */
export function Problems(): $CancellablePromise<$models.Problem[] | null> {
    return $Call.ByID(1559672226);
}

/**
 * Projects returns every registered project, in registry order.
 */
export function Projects(): $CancellablePromise<$models.ProjectView[] | null> {
    return $Call.ByID(3447663492);
}

/**
 * PromoteDraft turns a draft into a task in its own project.
 */
export function PromoteDraft(projectPath: string, draftID: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(222884257, projectPath, draftID);
}

/**
 * RegistryPath reports where the registry is read from, so the UI can name it.
 */
export function RegistryPath(): $CancellablePromise<string> {
    return $Call.ByID(2719443678);
}

/**
 * Reload re-reads the registry and rescans every project.
 * 
 * This is what the user reaches for when they have edited projects.yml by hand.
 */
export function Reload(): $CancellablePromise<$models.Problem[] | null> {
    return $Call.ByID(2009135923);
}

/**
 * RemoveLabel removes one label without touching the others.
 */
export function RemoveLabel(projectPath: string, taskID: string, label: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2631086464, projectPath, taskID, label);
}

/**
 * RemoveProject unregisters a folder. Nothing on disk is touched: Muster does
 * not delete backlogs, and a person who wanted the tasks gone would say so to
 * the CLI.
 */
export function RemoveProject(path: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(4106624107, path);
}

/**
 * ReviseDraft rewrites a draft, in its own project or another one.
 * 
 * Backlog.md has no `draft edit`: `task edit` refuses a DRAFT id outright.
 * So revising is capture-and-discard - the new note is created through the
 * CLI and the old one archived - which is also the only way to move a draft
 * between projects, since ids and files belong to one project.
 * 
 * The cost is that the new note is captured now, so its wait starts again.
 * That is stated in the interface rather than hidden, because the wait is the
 * number the inbox is for.
 * 
 * Order matters: create first, archive second. If the create fails there is
 * still a draft; if the archive fails there are two, which is visible and
 * fixable. The reverse could lose the note entirely.
 */
export function ReviseDraft(projectPath: string, draftID: string, edit: $models.DraftEdit): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2553231505, projectPath, draftID, edit);
}

/**
 * SaveProject rewrites one project's entry.
 */
export function SaveProject(path: string, edit: $models.ProjectEdit): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(3301300712, path, edit);
}

/**
 * SaveSettings stores the preferences and applies what can be applied at once.
 */
export function SaveSettings(next: settings$0.Settings): $CancellablePromise<$models.Problem[] | null> {
    return $Call.ByID(3275526566, next);
}

/**
 * Search looks through every entity of every project.
 */
export function Search(text: string, limit: number): $CancellablePromise<$models.SearchHit[] | null> {
    return $Call.ByID(1621044846, text, limit);
}

/**
 * SetAcceptanceCriteria replaces the whole list, which is what makes adding,
 * removing and reordering a single operation.
 */
export function SetAcceptanceCriteria(projectPath: string, taskID: string, items: string[] | null): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(956380688, projectPath, taskID, items);
}

/**
 * SetAssignee replaces a task's assignee.
 */
export function SetAssignee(projectPath: string, taskID: string, assignee: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2574606017, projectPath, taskID, assignee);
}

/**
 * SetPriority sets a task's priority.
 */
export function SetPriority(projectPath: string, taskID: string, priority: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(192072010, projectPath, taskID, priority);
}

/**
 * SetSection replaces one of a task's body sections.
 * 
 * The section names match what the parser exposes, so the frontend never has
 * to know which CLI flag writes which part of the file.
 */
export function SetSection(projectPath: string, taskID: string, section: string, text: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(869701961, projectPath, taskID, section, text);
}

/**
 * SetStatus moves a task to another status.
 */
export function SetStatus(projectPath: string, taskID: string, status: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(3922990440, projectPath, taskID, status);
}

/**
 * SetTitle renames a task.
 */
export function SetTitle(projectPath: string, taskID: string, title: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(1385653264, projectPath, taskID, title);
}

/**
 * Settings returns the application's own preferences.
 */
export function Settings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1296259787);
}

/**
 * StatusLists returns each project's declared status list, in registry order.
 * 
 * The board's columns are the union of these. Computing that union is the
 * board's own concern, with its own ordering rules.
 */
export function StatusLists(): $CancellablePromise<(string[] | null)[] | null> {
    return $Call.ByID(3906701921);
}

/**
 * Subtasks returns a task's subtasks, in the order the project scan produced.
 * 
 * Separate from the card payload on purpose: this is asked once when a task is
 * opened, where the board asks for every card at once.
 */
export function Subtasks(projectPath: string, kind: string, $class: string, id: string): $CancellablePromise<$models.TaskView[] | null> {
    return $Call.ByID(62383582, projectPath, kind, $class, id);
}

/**
 * Task returns one entity, or ok false when the ref names nothing.
 */
export function Task(projectPath: string, kind: string, $class: string, id: string): $CancellablePromise<[$models.TaskView, boolean]> {
    return $Call.ByID(1002097507, projectPath, kind, $class, id);
}

/**
 * Tasks returns every task matching a query, across every project.
 */
export function Tasks(q: $models.QueryInput): $CancellablePromise<$models.TaskView[] | null> {
    return $Call.ByID(386771504, q);
}

/**
 * WIP reports where a project is at or over an advisory limit.
 * 
 * It is a signal, never a rule: a limit that blocks a drag is a limit people
 * work around rather than one they act on.
 */
export function WIP(): $CancellablePromise<$models.WIPStatus[] | null> {
    return $Call.ByID(2613303266);
}
