// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoardService is the frontend's only entry point to the backend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddLabel adds a label to a task without touching the others.
 */
export function AddLabel(projectPath: string, taskID: string, label: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(3047498661, projectPath, taskID, label);
}

/**
 * CLIVersion reports the CLI version in use, empty when there is none.
 */
export function CLIVersion(): $CancellablePromise<string> {
    return $Call.ByID(3640242740);
}

/**
 * CanMove reports whether a task in a project may take a status.
 * 
 * A task can only ever hold a status its own project declares; anything else
 * would be a value the Backlog.md CLI itself rejects.
 */
export function CanMove(projectPath: string, status: string): $CancellablePromise<boolean> {
    return $Call.ByID(3472873825, projectPath, status);
}

/**
 * CaptureDraft writes text into a project's drafts.
 */
export function CaptureDraft(projectPath: string, title: string, description: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(4046319439, projectPath, title, description);
}

/**
 * CheckCriterion ticks or unticks an acceptance criterion by its 1-based index.
 */
export function CheckCriterion(projectPath: string, taskID: string, index: number, checked: boolean): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2097427485, projectPath, taskID, index, checked);
}

/**
 * CreateTask writes a new task into a project.
 */
export function CreateTask(input: $models.NewTaskInput): $CancellablePromise<$models.CreateResult> {
    return $Call.ByID(2184482871, input);
}

/**
 * FilterValues returns the distinct values of one field across every project,
 * for building filter menus.
 */
export function FilterValues(field: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3592693646, field);
}

/**
 * Layout returns the unified board columns.
 * 
 * Statuses are per-project configuration and projects do not agree, so the
 * columns are the union of every declared list. Muster never edits another
 * project's config to make its own view simpler.
 */
export function Layout(): $CancellablePromise<$models.BoardLayout> {
    return $Call.ByID(1111036648);
}

/**
 * Milestones returns every milestone across every project, in registry order.
 * 
 * A card carries its milestone as a bare id, which reads exactly like a task
 * id and says nothing. This is what lets the interface show the title instead.
 */
export function Milestones(): $CancellablePromise<$models.MilestoneView[] | null> {
    return $Call.ByID(4122282057);
}

/**
 * Problems returns everything currently wrong, worst first by kind.
 */
export function Problems(): $CancellablePromise<$models.Problem[] | null> {
    return $Call.ByID(1559672226);
}

/**
 * Projects returns every registered project, in registry order.
 */
export function Projects(): $CancellablePromise<$models.ProjectView[] | null> {
    return $Call.ByID(3447663492);
}

/**
 * RegistryPath reports where the registry is read from, so the UI can name it.
 */
export function RegistryPath(): $CancellablePromise<string> {
    return $Call.ByID(2719443678);
}

/**
 * Reload re-reads the registry and rescans every project.
 * 
 * This is what the user reaches for when they have edited projects.yml by hand.
 */
export function Reload(): $CancellablePromise<$models.Problem[] | null> {
    return $Call.ByID(2009135923);
}

/**
 * RemoveLabel removes one label without touching the others.
 */
export function RemoveLabel(projectPath: string, taskID: string, label: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2631086464, projectPath, taskID, label);
}

/**
 * SaveSettings stores the preferences and applies what can be applied at once.
 */
export function SaveSettings(next: settings$0.Settings): $CancellablePromise<$models.Problem[] | null> {
    return $Call.ByID(3275526566, next);
}

/**
 * SetAcceptanceCriteria replaces the whole list, which is what makes adding,
 * removing and reordering a single operation.
 */
export function SetAcceptanceCriteria(projectPath: string, taskID: string, items: string[] | null): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(956380688, projectPath, taskID, items);
}

/**
 * SetAssignee replaces a task's assignee.
 */
export function SetAssignee(projectPath: string, taskID: string, assignee: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(2574606017, projectPath, taskID, assignee);
}

/**
 * SetPriority sets a task's priority.
 */
export function SetPriority(projectPath: string, taskID: string, priority: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(192072010, projectPath, taskID, priority);
}

/**
 * SetSection replaces one of a task's body sections.
 * 
 * The section names match what the parser exposes, so the frontend never has
 * to know which CLI flag writes which part of the file.
 */
export function SetSection(projectPath: string, taskID: string, section: string, text: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(869701961, projectPath, taskID, section, text);
}

/**
 * SetStatus moves a task to another status.
 */
export function SetStatus(projectPath: string, taskID: string, status: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(3922990440, projectPath, taskID, status);
}

/**
 * SetTitle renames a task.
 */
export function SetTitle(projectPath: string, taskID: string, title: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(1385653264, projectPath, taskID, title);
}

/**
 * Settings returns the application's own preferences.
 */
export function Settings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1296259787);
}

/**
 * StatusLists returns each project's declared status list, in registry order.
 * 
 * The board's columns are the union of these. Computing that union is the
 * board's own concern, with its own ordering rules.
 */
export function StatusLists(): $CancellablePromise<(string[] | null)[] | null> {
    return $Call.ByID(3906701921);
}

/**
 * Task returns one entity, or ok false when the ref names nothing.
 */
export function Task(projectPath: string, kind: string, $class: string, id: string): $CancellablePromise<[$models.TaskView, boolean]> {
    return $Call.ByID(1002097507, projectPath, kind, $class, id);
}

/**
 * Tasks returns every task matching a query, across every project.
 */
export function Tasks(q: $models.QueryInput): $CancellablePromise<$models.TaskView[] | null> {
    return $Call.ByID(386771504, q);
}
