// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoardService is the frontend's only entry point to the backend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FilterValues returns the distinct values of one field across every project,
 * for building filter menus.
 */
export function FilterValues(field: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3592693646, field);
}

/**
 * Problems returns everything currently wrong, worst first by kind.
 */
export function Problems(): $CancellablePromise<$models.Problem[] | null> {
    return $Call.ByID(1559672226);
}

/**
 * Projects returns every registered project, in registry order.
 */
export function Projects(): $CancellablePromise<$models.ProjectView[] | null> {
    return $Call.ByID(3447663492);
}

/**
 * RegistryPath reports where the registry is read from, so the UI can name it.
 */
export function RegistryPath(): $CancellablePromise<string> {
    return $Call.ByID(2719443678);
}

/**
 * Reload re-reads the registry and rescans every project.
 * 
 * This is what the user reaches for when they have edited projects.yml by hand.
 */
export function Reload(): $CancellablePromise<$models.Problem[] | null> {
    return $Call.ByID(2009135923);
}

/**
 * StatusLists returns each project's declared status list, in registry order.
 * 
 * The board's columns are the union of these. Computing that union is the
 * board's own concern, with its own ordering rules.
 */
export function StatusLists(): $CancellablePromise<(string[] | null)[] | null> {
    return $Call.ByID(3906701921);
}

/**
 * Task returns one entity, or ok false when the ref names nothing.
 */
export function Task(projectPath: string, kind: string, $class: string, id: string): $CancellablePromise<[$models.TaskView, boolean]> {
    return $Call.ByID(1002097507, projectPath, kind, $class, id);
}

/**
 * Tasks returns every task matching a query, across every project.
 */
export function Tasks(q: $models.QueryInput): $CancellablePromise<$models.TaskView[] | null> {
    return $Call.ByID(386771504, q);
}
