// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backlog$0 from "../backlog/models.js";

/**
 * Problem is a failure the frontend can render.
 * 
 * Go errors cross the bridge as bare strings, which leaves the UI with nothing
 * to lay out and nothing to act on. A problem carries enough structure to be
 * shown as something other than a log line.
 */
export interface Problem {
    "kind": ProblemKind;

    /**
     * Title is one short line, suitable for a heading.
     */
    "title": string;

    /**
     * Detail is the underlying message.
     */
    "detail": string;

    /**
     * Path is the file or folder concerned, empty when none applies.
     */
    "path": string;
}

/**
 * ProblemKind classifies a failure so the UI can decide how loudly to show it.
 */
export enum ProblemKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ProblemCLI reports that the backlog CLI is missing or unusable. It is
     * recorded once at startup rather than raised again on every action.
     */
    ProblemCLI = "cli",

    /**
     * ProblemNoRegistry means there is no registry yet. This is first run, not
     * a fault, and the UI offers to add a project rather than showing an error.
     */
    ProblemNoRegistry = "no_registry",

    /**
     * ProblemRegistry means the registry itself could not be read.
     */
    ProblemRegistry = "registry",

    /**
     * ProblemProject means one project could not be loaded. The others are fine.
     */
    ProblemProject = "project",

    /**
     * ProblemFile means one file was skipped during a scan.
     */
    ProblemFile = "file",
};

/**
 * ProjectChanged is the payload of EventProjectChanged.
 */
export interface ProjectChanged {
    /**
     * Project is the registered project path, matching ProjectView.Path.
     */
    "project": string;
}

/**
 * ProjectView is one registered project as the frontend sees it.
 */
export interface ProjectView {
    "path": string;
    "name": string;
    "colour": string;
    "ok": boolean;
    "problem": string;
    "taskCount": number;
    "draftCount": number;

    /**
     * Statuses is what this project declares, in its own order. The board's
     * columns are the union of these across projects.
     */
    "statuses": string[] | null;

    /**
     * Layout is how the project's data directory was found.
     */
    "layout": string;
}

/**
 * QueryInput is the filter set the frontend sends. Every field is optional and
 * they combine with AND.
 */
export interface QueryInput {
    "kinds": string[] | null;
    "classes": string[] | null;
    "projects": string[] | null;
    "statuses": string[] | null;
    "milestones": string[] | null;
    "priorities": string[] | null;
    "types": string[] | null;
    "labels": string[] | null;
    "assignees": string[] | null;
    "text": string;
}

/**
 * TaskView is one task together with where it came from.
 * 
 * The entity is exposed as the domain type rather than flattened into a
 * hand-written shape: the TypeScript is generated from it, so a mirrored type
 * would only be a type that drifts.
 */
export interface TaskView {
    "project": string;
    "projectName": string;
    "projectColour": string;
    "kind": backlog$0.Kind;
    "class": backlog$0.Class;
    "id": string;
    "entity": backlog$0.Entity;
}

/**
 * WriteResult is what the frontend gets back from a write.
 * 
 * A write is not "did the call return": it is what the files say afterwards.
 * So this reports whether the CLI succeeded and carries the problem when it
 * did not, and the caller re-reads rather than assuming.
 */
export interface WriteResult {
    "ok": boolean;
    "problem": Problem | null;
}
