// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backlog$0 from "../backlog/models.js";

/**
 * AnalyticsView is the overview for one project, or for all of them.
 */
export interface AnalyticsView {
    /**
     * Project is empty on the entry that covers every project.
     */
    "project": string;
    "projectName": string;
    "tasks": number;
    "statuses": CountView[] | null;
    "priority": CountView[] | null;
    "types": CountView[] | null;
    "unprioritised": number;
    "averageAgeDays": number;
    "stale": TaskView[] | null;
    "blocked": BlockedView[] | null;
}

/**
 * BlockedView is a task waiting on something unfinished.
 */
export interface BlockedView {
    "task": TaskView;
    "on": string[] | null;
}

/**
 * BoardLayout is the board's columns and how they were decided.
 */
export interface BoardLayout {
    "columns": ColumnView[] | null;
    "conflicts": ConflictView[] | null;
}

/**
 * ColumnView is one column of the unified board.
 */
export interface ColumnView {
    "name": string;

    /**
     * Projects are the registered projects that declare this status. A project
     * absent from the list simply has no cell in this column.
     */
    "projects": string[] | null;
}

/**
 * ConflictView records a pair of statuses the projects ordered differently, so
 * the interface can explain an order that would otherwise look arbitrary.
 */
export interface ConflictView {
    "before": string;
    "after": string;
    "votes": number;
    "against": number;
}

/**
 * CountView is one label and how many things carry it.
 */
export interface CountView {
    "label": string;
    "total": number;
}

/**
 * CreateResult reports what happened, including the id the CLI assigned so the
 * interface can open the task it just made.
 */
export interface CreateResult {
    "ok": boolean;
    "taskId": string;
    "problem": Problem | null;
}

/**
 * DraftEdit is everything a draft can carry.
 * 
 * The whole field surface `task create --draft` accepts, not the four that
 * `draft create` does: a note that cannot be given a priority or a milestone
 * until it stops being a note is a note nobody triages.
 */
export interface DraftEdit {
    "title": string;
    "description": string;
    "labels": string[] | null;
    "assignee": string;
    "priority": string;
    "type": string;
    "milestone": string;

    /**
     * AcceptanceCriteria are added in order, as items.
     */
    "acceptanceCriteria": string[] | null;

    /**
     * Project is where the draft should end up. Empty means where it is.
     */
    "project": string;
}

/**
 * DraftView is one captured note waiting to be dealt with.
 * 
 * Carries the whole entity like every other view, plus the one number the
 * inbox exists to make visible: how long it has been sitting there.
 */
export interface DraftView {
    "project": string;
    "projectName": string;
    "projectColour": string;
    "kind": backlog$0.Kind;
    "class": backlog$0.Class;
    "id": string;
    "entity": backlog$0.Entity;

    /**
     * Family is present only for a task that has a parent or subtasks, which
     * is 92 of the 712 in the author's projects. Nil for everything else, so
     * the relationship costs nothing on the cards that have none.
     */
    "family"?: FamilyView | null;

    /**
     * WaitingDays is whole days since capture, or -1 when the file carries no
     * created_date. Counted rather than formatted here, so the interface can
     * say "today" without parsing anything back.
     */
    "waitingDays": number;
}

/**
 * EntityRef names one entity, in the shape the interface uses to open it.
 */
export interface EntityRef {
    "project": string;
    "kind": backlog$0.Kind;
    "class": backlog$0.Class;
    "id": string;
}

/**
 * FamilyView is what a card needs to show a parent or subtask relationship
 * without asking for anything else.
 * 
 * Counts rather than the subtasks themselves: the board asks for hundreds of
 * cards at once and a card only ever shows how many there are. The panel asks
 * for the list separately, once, when a task is opened.
 */
export interface FamilyView {
    /**
     * Parent is where the parent lives, which is not always the same
     * directory the child is in. Nil when the task has no parent, and also
     * when it declares one that no file answers to - the declared id is on the
     * entity either way.
     */
    "parent"?: EntityRef | null;
    "parentTitle"?: string;

    /**
     * Done and Total count subtasks. Archived subtasks are in neither, since
     * the board does not show them.
     */
    "done": number;
    "total": number;
}

/**
 * FolderView is what is known about a folder before it is registered.
 * 
 * The answer decides what is offered rather than what is asked: a folder that
 * already holds a backlog wants registering, one that does not wants
 * initialising, and one that is not a repository wants the no-git path chosen
 * for it instead of being asked a question it would fail on.
 */
export interface FolderView {
    /**
     * Path is the folder, resolved the way the registry would resolve it.
     */
    "path": string;

    /**
     * Name is what the project would be called if nothing overrode it.
     */
    "name": string;

    /**
     * Exists and IsDir are separate: a file is a different mistake from a
     * path that is not there at all.
     */
    "exists": boolean;
    "isDir": boolean;

    /**
     * IsGit reports a git repository at the folder itself.
     */
    "isGit": boolean;

    /**
     * HasBacklog reports a Backlog.md project already in place.
     */
    "hasBacklog": boolean;

    /**
     * Layout is how that project's data directory was found, when there is one.
     */
    "layout": string;

    /**
     * Registered reports that Muster already holds this folder.
     */
    "registered": boolean;

    /**
     * Problem explains a folder that cannot be used at all.
     */
    "problem": string;
}

/**
 * InitFolder is the form behind `backlog init`.
 * 
 * Every field is optional: the CLI is run with --defaults, so anything left
 * empty is answered by Backlog.md itself rather than by a default of Muster's
 * own invention.
 */
export interface InitFolder {
    "path": string;
    "name": string;
    "backlogDir": string;
    "configLocation": string;
    "taskPrefix": string;
    "zeroPaddedIds": number;
    "noGit": boolean;
    "agentInstructions": string;
    "integrationMode": string;

    /**
     * Colour is Muster's own, applied when the new project is registered.
     */
    "colour": string;
}

/**
 * MilestoneView is one milestone, with enough to show it by name and to see
 * how far along it is.
 */
export interface MilestoneView {
    "project": string;
    "projectName": string;
    "id": string;
    "title": string;

    /**
     * Total and Done count the tasks assigned to it in that project.
     */
    "total": number;
    "done": number;
}

/**
 * NewTaskInput is the create form as the frontend sends it.
 */
export interface NewTaskInput {
    "project": string;
    "title": string;
    "description": string;
    "status": string;
    "priority": string;
    "type": string;
    "milestone": string;
    "assignee": string;
    "labels": string[] | null;
    "acceptanceCriteria": string[] | null;
}

/**
 * Problem is a failure the frontend can render.
 * 
 * Go errors cross the bridge as bare strings, which leaves the UI with nothing
 * to lay out and nothing to act on. A problem carries enough structure to be
 * shown as something other than a log line.
 */
export interface Problem {
    "kind": ProblemKind;

    /**
     * Title is one short line, suitable for a heading.
     */
    "title": string;

    /**
     * Detail is the underlying message.
     */
    "detail": string;

    /**
     * Path is the file or folder concerned, empty when none applies.
     */
    "path": string;
}

/**
 * ProblemKind classifies a failure so the UI can decide how loudly to show it.
 */
export enum ProblemKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ProblemNoRegistry means there is no registry yet. This is first run, not
     * a fault, and the UI offers to add a project rather than showing an error.
     */
    ProblemNoRegistry = "no_registry",

    /**
     * ProblemRegistry means the registry itself could not be read.
     */
    ProblemRegistry = "registry",

    /**
     * ProblemProject means one project could not be loaded. The others are fine.
     */
    ProblemProject = "project",

    /**
     * ProblemFile means one file was skipped during a scan.
     */
    ProblemFile = "file",

    /**
     * ProblemCLI reports that the backlog CLI is missing or unusable. It is
     * recorded once at startup rather than raised again on every action.
     */
    ProblemCLI = "cli",
};

/**
 * ProjectChanged is the payload of EventProjectChanged.
 */
export interface ProjectChanged {
    /**
     * Project is the registered project path, matching ProjectView.Path.
     */
    "project": string;
}

/**
 * ProjectEdit is the whole of what the registry holds about one project.
 * 
 * Sent complete rather than as a change, because the entry is rewritten as a
 * whole: a partial edit would have to guess what the missing fields meant.
 */
export interface ProjectEdit {
    "name": string;
    "colour": string;
    "hidden": boolean;
}

/**
 * ProjectView is one registered project as the frontend sees it.
 */
export interface ProjectView {
    "path": string;
    "name": string;
    "colour": string;
    "ok": boolean;
    "problem": string;
    "taskCount": number;
    "draftCount": number;

    /**
     * Statuses is what this project declares, in its own order. The board's
     * columns are the union of these across projects.
     */
    "statuses": string[] | null;

    /**
     * Priorities and Types are what this project configures. They are read
     * from the project rather than assumed, because both are configurable and
     * a hardcoded list would be wrong the first time someone changes one.
     */
    "priorities": string[] | null;
    "types": string[] | null;

    /**
     * Layout is how the project's data directory was found.
     */
    "layout": string;

    /**
     * Hidden keeps the project out of the board, the lists, search and the
     * figures without unregistering it. The Projects screen still shows it,
     * with everything it holds.
     */
    "hidden": boolean;
}

/**
 * QueryInput is the filter set the frontend sends. Every field is optional and
 * they combine with AND.
 */
export interface QueryInput {
    "kinds": string[] | null;
    "classes": string[] | null;
    "projects": string[] | null;
    "statuses": string[] | null;
    "milestones": string[] | null;
    "priorities": string[] | null;
    "types": string[] | null;
    "labels": string[] | null;
    "assignees": string[] | null;
    "text": string;
}

/**
 * SearchHit is one search result as the frontend sees it.
 */
export interface SearchHit {
    "project": string;
    "projectName": string;
    "kind": backlog$0.Kind;
    "class": backlog$0.Class;
    "id": string;
    "title": string;

    /**
     * Field says where the match was: title, id or body.
     */
    "field": string;

    /**
     * Excerpt is the matching text with a little around it.
     */
    "excerpt": string;
}

/**
 * TaskView is one task together with where it came from.
 * 
 * The entity is exposed as the domain type rather than flattened into a
 * hand-written shape: the TypeScript is generated from it, so a mirrored type
 * would only be a type that drifts.
 */
export interface TaskView {
    "project": string;
    "projectName": string;
    "projectColour": string;
    "kind": backlog$0.Kind;
    "class": backlog$0.Class;
    "id": string;
    "entity": backlog$0.Entity;

    /**
     * Family is present only for a task that has a parent or subtasks, which
     * is 92 of the 712 in the author's projects. Nil for everything else, so
     * the relationship costs nothing on the cards that have none.
     */
    "family"?: FamilyView | null;
}

/**
 * WIPStatus is one column's load against its advisory limit.
 */
export interface WIPStatus {
    "project": string;
    "projectName": string;
    "status": string;
    "count": number;
    "limit": number;
    "over": boolean;
}

/**
 * WriteResult is what the frontend gets back from a write.
 * 
 * A write is not "did the call return": it is what the files say afterwards.
 * So this reports whether the CLI succeeded and carries the problem when it
 * did not, and the caller re-reads rather than assuming.
 */
export interface WriteResult {
    "ok": boolean;
    "problem": Problem | null;
}
