// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the root service bound into the frontend. Feature services are
 * added alongside it as they arrive; this one carries only what the shell needs
 * before any project is loaded.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * AppVersion reports the version this binary was built from.
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(711637649);
}
